### PR TITLE
oss: Fix CPU spinning 100%

### PR DESCRIPTION
**Pull request by khng300**
As for output-only stream we do not wait on the buffer at all, the CPU usage would spin to 100%.

I would like this PR to be backported to Firefox 85 as well.

### CODE REVIEW

**Comment by khng300** [comment]
@jbeich Please test this patch on firefox 85, thanks.

**Comment by jbeich** [comment]
Seems to work fine inside 11.4 i386 and 12.1 amd64 jails.

**Comment by padenot** [comment]
> I would like this PR to be backported to Firefox 85 as well.

I've pinged the release managers about this. We're _very_ late in the release process for 85 (5 days until uplift: https://whattrainisitnow.com/), and it's not my call, but if we can, I'll prepare the backport.

**Review by padenot — APPROVED** [review]
In any case, I'm merging this now, as it looks fine to my non-knowledgeable eyes, and Jan says it works.

**Comment by khng300** [comment]
Thanks for the help on that request.

Ka Ho

**Comment by padenot** [comment]
They say it's too late, so you'll have to carry a patch for this one. I'm merging it to `mozilla-central` as we speak however: https://bugzilla.mozilla.org/show_bug.cgi?id=1687487.

**Comment by khng300** [comment]
> They say it's too late, so you'll have to carry a patch for this one. I'm merging it to `mozilla-central` as we speak however: https://bugzilla.mozilla.org/show_bug.cgi?id=1687487.

Thanks for the help. I am okay with carrying downstream patches on the ports side.

**Comment by padenot** [comment]
Final update on this: I just queued this for landing to `mozilla-central`.

**Pull request merged**
