### PR TITLE
OSS output support

### PR DESCRIPTION
**Pull request by s3erios**
Seems it works fine in Firefox 30 (FreeBSD, Lubuntu). However I'm not sure about latency - now it is in the range ( latency, (5/4) \* latency ) (otherwise test_drain will fail).

### CODE REVIEW

**Comment by MrMormon** [comment]
Update?

**Comment by kinetiknz** [comment]
What I said in https://github.com/kinetiknz/cubeb/pull/41#issuecomment-55691538, which is:

Someone (not me) needs to resolve the situation where we've got this implementation and another attached to https://bugzilla.mozilla.org/show_bug.cgi?id=1021761.  The latter has had more recent activity, but as someone with no time to investigate anything related to OSS I don't know which implementation is the better option.

**Comment by debdrup** [comment]
Since FreeBSD has been added to the CI, and nia has pointed out that the bug issue that [you're referring](https://github.com/kinetiknz/cubeb/pull/41#issuecomment-200061842) is the same thing nia has been working on here, perhaps something can be done about this now?

**Comment by debdrup** [comment]
Any chance for getting this code landed, now that FreeBSD is in the CI as of #589 ?

**Comment by mekanix** [comment]
I'd like to continue work on this (or other) patch. I would need some guidance, though, on how to test it (in browser or otherwise). Also, any and all tips and preferences are welcome!

**Comment by khng300** [comment]
I will work on it @debdrup :)

**Comment by mekanix** [comment]
I understand that latency is the problem with OSS, and on FreeBSD Drumgizmo had same problems. One of the problems was:
```
sysctl kern.timecounter.alloweddeviation=0 # by default it's 5
```
There are more interesting tunables which might affect FreeBSD OSS and I described them in a [blog post](https://meka.rs/blog/2017/01/25/sing-beastie-sing/). I truly hope this helps!

**Comment by khng300** [comment]
I just rewrote the sunaudio backend to be ossaudio. You can track the progress here: https://github.com/khng300/cubeb/tree/oss-update
It is yet finished, so don't expect it can run properly now. :)

**Comment by khng300** [comment]
I guess people tracking this PR might be interested in https://github.com/kinetiknz/cubeb/pull/600 as well :)

**Comment by kinetiknz** [comment]
Closing.  OSS support was merged via https://github.com/mozilla/cubeb/pull/600.

**Comment by Nuc1eoN** [comment]
@kinetiknz does this include OSSv4 support? Afaik FreeBSD's OSS and OSSv4 is not the same.
And iirc this PR here was about OSSv4?

**Comment by khng300** [comment]
#600 supports OSSv4 only.

**Comment by Nuc1eoN** [comment]
@khng300 Oh ok thanks! For some reason I thought BSDs run on a modified version of the older OSSv3

**Comment by Nuc1eoN** [comment]
Would this also include Linux support? And starting from which Firefox version has OSSv4 support been integrated if I may ask? :)

**Comment by khng300** [comment]
Currently there's no plan to make it works on Linux, given that OSSv4 API actually varies on different platforms. I am not surprised if it works though.

**Comment by kinetiknz** [comment]
Any changes needed to support Linux could be integrated (without negatively affecting the existing support) into the merged OSS backend.

As far as Firefox support, there are no plans to ship the OSS backend.  Per https://github.com/mozilla/cubeb/wiki/Backend-Support, only the Tier-1 backends are directly supported in Firefox.  Community contributions for anything else are welcomed, though!

**Comment by Nuc1eoN** [comment]
> As far as Firefox support, there are no plans to ship the OSS backend. Per https://github.com/mozilla/cubeb/wiki/Backend-Support, only the Tier-1 backends are directly supported in Firefox. Community contributions for anything else are welcomed, though!

I am struggling to understand this completely. So does this mean OSS in firefox is not active? Why would it not be shipped if it's implemented in cubeb?

**Comment by khng300** [comment]
It is active on FreeBSD.

**Comment by kinetiknz** [comment]
Right - sorry for the confusion!  I was referring only to the official Mozilla builds.

**Pull request closed without merging**
